language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAIT4X4NDGM2WVL6VA
  - DOCKER_USERNAME=octoblu
  - DEPLOY_APPLICATION_NAME=vote-octoblu-com
  - DEPLOY_REGION=us-west-2
  - DEPLOY_BUCKET=octoblu-deploy
  - DEPLOYMENT_GROUP=master
  - DEPLOY_KEY=vote-octoblu-com/vote-octoblu-com-$TRAVIS_COMMIT.zip
  - secure: hXqHJUr5Qf8HgsdcKwnksZD81zxjCkhC4XPUVdS7ptf3k5MxWkiQlfXXPy2YIZI5+xpXV0QTghrDG6INdX7SdTg9lup/yn5ybwTLmvV9+6M77qG4KYU0f35xKzQErkV0KklQdE8J2/ZpvP2BGPb1PzDvNgtz/EgwGVdxVDMiRUk=
  - secure: XqpvG+cas5zzGdk7aA4psloC1/h5aCslFMJre1bFc0xM4Zn7MzLqHAU/ybvoBeXlmgDqPmwz50z/7MsWNSHmjiA+xoRoHYj9hjSqL+0wsR5fxP+3LrlNKdNO64qPwQmdONNoAWAErmP66X00T0ELOiC0ydQqb77DlrlPkbXb/4k=
after_success:
- .kubernetes/travis_after_success
deploy:
- provider: s3
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key: &70307617732360
    secure: cZ360f8T8WVqPOc3lF02X7Ara3/e/lA5NIkSSBlliCAbni0NFoLf6LOB35U3G21mkjIO65ch1KIaDWbtLQlhiePcTlxK+NaWdH9NuoABfUcQB9zJtpt1iHRAHH5ALHwy+qYQlJ+jQf6svF8kVfoRSW+7Irpu2Mj+C81F7PVLLvw=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: octoblu-deploy
  on:
    branch: master
- provider: codedeploy
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key: *70307617732360
  bucket: octoblu-deploy
  key: docker-builder/vote-octoblu-com-$TRAVIS_COMMIT.zip
  bundle_type: zip
  region: us-west-2
  application: docker-builder
  deployment_group: vote-octoblu-com
  on:
    branch: master
